print ("Hello World")
print ("Hello World, my name is <Emma> and I love Python!")
print ("Hello World, my name is Emma and I love Python!")
userName = input ("Hello! Please enter you name!")
print ("Hello", userName, "nice to meet you")
userName = input ("Hello! Emma!")
print ("Hello" , Emma, "nice to meet you")
